categories = [
    {
        "id": 1,
        "name": "Electronics",
    },
    {
        "id": 2,
        "name": "Smartphones",
    },
    {
        "id": 3,
        "name": "Appliances",
    },
    {
        "id": 4,
        "name": "Footwear",
    },
    {
        "id": 5,
        "name": "Accessories",
    },
    {
        "id": 6,
        "name": "Audio",
    },
    {
        "id": 7,
        "name": "Gaming",
    },
    {
        "id": 8,
        "name": "Smart Home",
    },
]

products = [
    {
        "id": 1,
        "name": "Dell Inspiron Laptop",
        "category": "Electronics",
        "price": 799.99,
        "stock": 15,
        "available": True,
    },
    {
        "id": 2,
        "name": "Samsung Galaxy A54",
        "category": "Smartphones",
        "price": 349.99,
        "stock": 30,
        "available": True,
    },
    {
        "id": 3,
        "name": "Arno Electric Coffee Maker",
        "category": "Appliances",
        "price": 39.99,
        "stock": 12,
        "available": True,
    },
    {
        "id": 4,
        "name": "Nike Revolution Running Shoes",
        "category": "Footwear",
        "price": 69.99,
        "stock": 25,
        "available": True,
    },
    {
        "id": 5,
        "name": "SwissGear Backpack",
        "category": "Accessories",
        "price": 49.99,
        "stock": 10,
        "available": True,
    },
    {
        "id": 6,
        "name": "LG 24'' Full HD Monitor",
        "category": "Electronics",
        "price": 159.99,
        "stock": 0,
        "available": False,
    },
    {
        "id": 7,
        "name": "JBL Tune 500 Headphones",
        "category": "Audio",
        "price": 29.99,
        "stock": 40,
        "available": True,
    },
    {
        "id": 8,
        "name": "Logitech G203 Gaming Mouse",
        "category": "Electronics",
        "price": 24.99,
        "stock": 18,
        "available": True,
    },
    {
        "id": 9,
        "name": "Canon EOS Rebel T7 Camera",
        "category": "Photography",
        "price": 449.99,
        "stock": 0,
        "available": False,
    },
    {
        "id": 10,
        "name": "Sony PlayStation 5",
        "category": "Gaming",
        "price": 499.99,
        "stock": 5,
        "available": True,
    },
    {
        "id": 11,
        "name": "Apple Watch SE",
        "category": "Wearables",
        "price": 279.0,
        "stock": 20,
        "available": True,
    },
    {
        "id": 12,
        "name": "Google Nest Mini",
        "category": "Smart Home",
        "price": 49.0,
        "stock": 35,
        "available": True,
    },
    {
        "id": 13,
        "name": "HP DeskJet 2755e Printer",
        "category": "Office Supplies",
        "price": 69.99,
        "stock": 7,
        "available": True,
    },
    {
        "id": 14,
        "name": "Xbox Wireless Controller",
        "category": "Gaming",
        "price": 59.99,
        "stock": 22,
        "available": True,
    },
    {
        "id": 15,
        "name": "Kindle Paperwhite",
        "category": "Books & eReaders",
        "price": 129.99,
        "stock": 13,
        "available": True,
    },
    {
        "id": 16,
        "name": "Samsung 4K Smart TV 55''",
        "category": "Electronics",
        "price": 599.99,
        "stock": 6,
        "available": True,
    },
    {
        "id": 17,
        "name": "Amazon Echo Show 5",
        "category": "Smart Home",
        "price": 89.99,
        "stock": 11,
        "available": True,
    },
    {
        "id": 18,
        "name": "Fitbit Charge 5",
        "category": "Wearables",
        "price": 119.95,
        "stock": 19,
        "available": True,
    },
    {
        "id": 19,
        "name": "Asus ROG Gaming Laptop",
        "category": "Electronics",
        "price": 1199.99,
        "stock": 0,
        "available": False,
    },
    {
        "id": 20,
        "name": "GoPro HERO10",
        "category": "Photography",
        "price": 399.99,
        "stock": 9,
        "available": True,
    },
    {
        "id": 21,
        "name": "Anker PowerCore Portable Charger",
        "category": "Accessories",
        "price": 39.99,
        "stock": 50,
        "available": True,
    },
    {
        "id": 22,
        "name": "Beats Studio3 Wireless Headphones",
        "category": "Audio",
        "price": 249.99,
        "stock": 14,
        "available": True,
    },
    {
        "id": 23,
        "name": "Razer BlackWidow V3 Keyboard",
        "category": "Electronics",
        "price": 139.99,
        "stock": 16,
        "available": True,
    },
    {
        "id": 24,
        "name": "Nikon D3500 DSLR Camera",
        "category": "Photography",
        "price": 499.99,
        "stock": 0,
        "available": False,
    },
    {
        "id": 25,
        "name": "Bose QuietComfort Earbuds",
        "category": "Audio",
        "price": 199.0,
        "stock": 21,
        "available": True,
    },
    {
        "id": 26,
        "name": "Samsung T7 Portable SSD 1TB",
        "category": "Storage",
        "price": 109.99,
        "stock": 28,
        "available": True,
    },
    {
        "id": 27,
        "name": "Garmin Forerunner 245",
        "category": "Wearables",
        "price": 249.95,
        "stock": 8,
        "available": True,
    },
    {
        "id": 28,
        "name": "TP-Link Wi-Fi 6 Router",
        "category": "Networking",
        "price": 89.99,
        "stock": 33,
        "available": True,
    },
    {
        "id": 29,
        "name": "Apple AirPods Pro",
        "category": "Audio",
        "price": 249.0,
        "stock": 27,
        "available": True,
    },
    {
        "id": 30,
        "name": "Microsoft Surface Go 3",
        "category": "Electronics",
        "price": 399.99,
        "stock": 0,
        "available": False,
    },
    {
        "id": 31,
        "name": "Seagate Expansion 2TB HDD",
        "category": "Storage",
        "price": 59.99,
        "stock": 44,
        "available": True,
    },
    {
        "id": 32,
        "name": "Acer Nitro 5 Gaming Laptop",
        "category": "Electronics",
        "price": 799.99,
        "stock": 10,
        "available": True,
    },
    {
        "id": 33,
        "name": "DJI Mini 2 Drone",
        "category": "Drones",
        "price": 449.99,
        "stock": 6,
        "available": True,
    },
    {
        "id": 34,
        "name": "Philips Hue Starter Kit",
        "category": "Smart Home",
        "price": 179.99,
        "stock": 12,
        "available": True,
    },
    {
        "id": 35,
        "name": "Echo Dot (5th Gen)",
        "category": "Smart Home",
        "price": 49.99,
        "stock": 30,
        "available": True,
    },
    {
        "id": 36,
        "name": "Sony WH-1000XM4 Headphones",
        "category": "Audio",
        "price": 278.0,
        "stock": 13,
        "available": True,
    },
    {
        "id": 37,
        "name": "Roku Streaming Stick 4K",
        "category": "Streaming",
        "price": 39.99,
        "stock": 31,
        "available": True,
    },
    {
        "id": 38,
        "name": "Tile Mate Bluetooth Tracker",
        "category": "Accessories",
        "price": 24.99,
        "stock": 25,
        "available": True,
    },
    {
        "id": 39,
        "name": "SteelSeries Rival 5 Mouse",
        "category": "Electronics",
        "price": 59.99,
        "stock": 19,
        "available": True,
    },
    {
        "id": 40,
        "name": "WD Black SN850X 1TB SSD",
        "category": "Storage",
        "price": 119.99,
        "stock": 14,
        "available": True,
    },
]
